project:
  type: website

website:
  title: "Slides: Software development - good practices, tips & tools"
  site-url: https://patricia-ternes.github.io/slides_SD_tips_tools
  description: "Slides for the "Software development - good practices, tips & tools" Training."
